/**
 * Learning Centre — talking-head explainers.
 *
 * A growing collection of short videos on the systems behind AI delivery,
 * cross-posted from LinkedIn. Rendered in a 90s-explainer "Knowledge
 * Network" aesthetic on the home page via <LearningCentre/>.
 *
 * Conventions:
 *   - `volume` is the issue number, zero-padded; controls sort order.
 *   - `slug` matches the file basename in /public/videos/:
 *       /public/videos/<slug>.mp4
 *       /public/videos/<slug>.poster.jpg
 *     (Generated by `pnpm video:optimize <source.mp4>`.)
 *   - `duration` is human-readable. `seconds` is the canonical truth.
 *   - `topic` is the eyebrow / VHS-spine label. Keep it short.
 *   - `summary` is one sentence — what the viewer will learn.
 *   - `linkedin` is optional; renders a "discuss on LinkedIn ↗" link.
 *   - `status: "live" | "soon"` — "soon" cards render as placeholder
 *     tape spines so the section reads as a series, not a one-off.
 */

export type VideoStatus = "live" | "soon";

export type LearningVideo = {
  slug: string;
  volume: string;
  topic: string;
  title: string;
  /** Optional Eiko italic word inside the title. */
  italic?: string;
  summary: string;
  duration: string;
  seconds: number;
  recorded: string;
  status: VideoStatus;
  linkedin?: string;
};

export const VIDEOS: LearningVideo[] = [
  {
    slug: "memory-architectures",
    volume: "01",
    topic: "AI · Memory",
    title: "Memory architectures for AI agents.",
    italic: "Memory",
    summary:
      "Short, long, episodic, semantic — what each layer is actually for, and how the good agent systems wire them together.",
    duration: "1:43",
    seconds: 103,
    recorded: "May 2025",
    status: "live",
  },
  {
    slug: "next-up",
    volume: "02",
    topic: "Coming soon",
    title: "More transmissions inbound.",
    summary:
      "Talking-head explainers ship semi-frequently — typically the week after I post them to LinkedIn. Subscribe there to catch the next drop.",
    duration: "—:—",
    seconds: 0,
    recorded: "soon",
    status: "soon",
  },
];
