name: Build and Deploy [DEV]

on:
  push:
    branches: [ master ]

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:

  deploy:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configure Committer
        run: |
          git config user.name "curtisblanchette"
          git config user.email "<curtis@4iiz.com>"

      - name: Build Dist
        run: npm run build

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-west-2"
        run: aws s3 sync ./build s3://www.curtisblanchette.com --delete --region ${AWS_REGION}

      - name: Create CloudFront Cache Invalidation
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.CLOUDFRONT_ID }}
          PATHS: "/*"
          AWS_REGION: "us-west-2"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
